name: ⛑️ Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  cancel-in-progress: true
  group: lint-${{ github.ref }}

jobs:
  code:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint

  docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: Dockerfile
          verbose: true
